services:
  prosjekt:
    image: ${DOCKER_REGISTRY-}prosjekt
    build:
      context: .
      dockerfile: Prosjekt/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mariadbcontainer;port=3306;database=mysql;user=root;password=Gruppe12!;
    networks:
      - appnet

networks:
  appnet:
    external: true
    name: appnet